# Generated by Django 5.0.4 on 2024-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
